import { defineTool } from "@lovable.dev/mcp-js";

const STYLES = [
  { id: "classic", label: "Classic", description: "Cel-shaded, vibrant colors, expressive eyes, clean lineart." },
  { id: "manga", label: "Manga", description: "Black-and-white manga with detailed ink linework and screentones." },
  { id: "cyberpunk", label: "Cyberpunk", description: "Neon lights, futuristic city, glowing pink and cyan accents." },
  { id: "ghibli", label: "Ghibli", description: "Soft painterly hand-drawn anime, watercolor backgrounds." },
  { id: "kawaii", label: "Kawaii", description: "Chibi, pastel palette, big sparkling eyes, super cute." },
  { id: "samurai", label: "Samurai", description: "Feudal Japan samurai, traditional dress, ink-wash cinematic look." },
  { id: "disney", label: "Disney", description: "Polished 3D feature film look, expressive eyes, cinematic warm lighting." },
  { id: "pixar", label: "Pixar 3D", description: "High-end 3D animation, plush textures, soft rounded features." },
  { id: "simpsons", label: "Yellow Cartoon", description: "Yellow-skin sitcom cartoon, thick outlines, flat colors, overbite." },
  { id: "comic", label: "Comic Book", description: "American comic book: bold ink, halftone dots, vivid primaries." },
  { id: "pixel", label: "Pixel Art", description: "16-bit retro pixel-art sprite portrait." },
  { id: "watercolor", label: "Watercolor", description: "Watercolor illustration with soft paint washes and pastel colors." },
  { id: "chibi", label: "Chibi", description: "Chibi caricature: huge head, tiny body, sticker-cute." },
  { id: "retro90s", label: "Retro 90s", description: "Retro 90s Saturday morning cartoon, bold outlines, VHS grain." },
  { id: "gothic", label: "Gothic", description: "Gothic dark fantasy: moody purples, lace, Tim Burton influence." },
  { id: "lego", label: "LEGO", description: "LEGO minifigure plastic brick portrait." },
  { id: "claymation", label: "Claymation", description: "Clay stop-motion with visible fingerprints and imperfect texture." },
  { id: "papercraft", label: "Paper Craft", description: "Layered construction-paper collage look." },
  { id: "mecha", label: "Mecha", description: "Mecha anime with robotic armor and glowing energy." },
  { id: "shonen", label: "Shonen", description: "Action shonen anime: spiky hair, aura, motion lines." },
  { id: "shojo", label: "Shojo", description: "Shojo romance anime: sparkles, flowers, huge eyes." },
  { id: "vaporwave", label: "Vaporwave", description: "80s vaporwave: pink/cyan grids and Greek statue vibe." },
  { id: "lowpoly", label: "Low Poly", description: "Faceted low-poly 3D geometric portrait." },
  { id: "sketch", label: "Pencil Sketch", description: "Graphite pencil sketch with hatching." },
  { id: "oil", label: "Oil Painting", description: "Classical renaissance oil painting with brush strokes." },
  { id: "ukiyoe", label: "Ukiyo-e", description: "Japanese woodblock print with flat colors and bold outlines." },
  { id: "popart", label: "Pop Art", description: "Warhol/Lichtenstein pop art with halftone dots." },
  { id: "graffiti", label: "Graffiti", description: "Urban street graffiti spray-paint style." },
  { id: "noir", label: "Film Noir", description: "1940s black-and-white noir with venetian blind shadows." },
  { id: "steampunk", label: "Steampunk", description: "Brass goggles, gears, Victorian industrial." },
  { id: "fantasy", label: "Fantasy", description: "High fantasy digital painting: armor, magic, epic landscape." },
  { id: "stopmotion", label: "Stop Motion", description: "Puppet-film stop-motion with felt and wool textures." },
  { id: "felt", label: "Felt", description: "Handmade felt doll with fuzzy wool and stitched features." },
  { id: "plush", label: "Plush Toy", description: "Cute stuffed plush toy with button eyes." },
  { id: "origami", label: "Origami", description: "Folded paper origami character with sharp creases." },
  { id: "sticker", label: "Sticker", description: "Die-cut vinyl sticker with thick white outline." },
  { id: "tattoo", label: "Tattoo Flash", description: "Old-school American traditional tattoo flash." },
  { id: "mosaic", label: "Mosaic", description: "Ceramic-tile mosaic portrait with grout lines." },
  { id: "stainedglass", label: "Stained Glass", description: "Cathedral stained-glass with lead lines." },
  { id: "storybook", label: "Storybook", description: "Whimsical children's storybook watercolor." },
  { id: "artdeco", label: "Art Deco", description: "1920s Gatsby-era gold geometric glamour." },
  { id: "minimalist", label: "Minimalist", description: "Single continuous line drawing on white." },
  { id: "holographic", label: "Holographic", description: "Iridescent chrome/holographic rainbow foil." },
  { id: "superflat", label: "Superflat", description: "Murakami superflat: flat vivid colors, smiling flowers." },
  { id: "crayon", label: "Crayon", description: "Child's waxy crayon drawing on paper." },
];

export default defineTool({
  name: "list_anime_styles",
  title: "List anime styles",
  description: "List every cartoon and anime art style AniGen can transform a photo into (45 total), with id, label and short description.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(STYLES, null, 2) }],
    structuredContent: { styles: STYLES },
  }),
});
